CREATE TABLE [dbo].[Raw]
(
	[RawId] BIGINT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	[StaffID] BIGINT NULL,
	[TID] BIGINT NULL,
	[TimeIN] DATETIME NULL,
	[TimeID] BIGINT NULL,
	[LogType] SMALLINT NULL,
	[FlagProses] BIT NULL,
	[EnrollID] NVARCHAR(50) NULL,
	[GRawID] BIGINT NULL,
	[GCawID] BIGINT NULL,
	[LRawID] BIGINT NULL,
	[BranchID] BIGINT NULL,
	[VerifyMode] INT NULL,
	[Error] BIT NULL	
)